create table product(
id char(5),
size numeric(10,2) not null,
category varchar(10) not null,
pname varchar(200) not null,
image varchar(40) not null,
additioninfo varchar(500) not null,

primary key(id));



insert into product(id,size,category,pname,additioninfo,image) values('34111', 32.0, 'beverages','almondmilk','80 calories per serving','almondmilk.png' ),
('34112', 32.0, 'beverages', 'apple juice','60 calories per serving','applejuice.png' ),
('34113', 32.0, 'beverages', 'brewed tea','80 calories per serving','brewedtea.png'),
('34114', 12, 'beverages', 'coca cola','100 calories per can','cocacola 12count 12oz.png'),
('34115', 12.0, 'beverages', 'coconut water','60 calories per serving','coconutwater.png'), 
('34116',12, 'beverages', 'fiji water','0 calories per serving','FijiWater.png'),
('34117', 6, 'beverages', 'gatorade','30 calories per serving ','gatorade.png'),
('34118', 12,'beverages', 'ginger Ale','30 calories per serving', 'GingerAle.png'), 
('34119', 32, 'beverages', 'lemonade','20 calories per serving', 'lemonade.png'), 
('34120', 12, 'beverages', 'lipton tea','60 calories per serving','liptonTea.png'),
('34121', 1, 'beverages','orange juice','20 calories per serving','orange juice.png'),
('34122', 1, 'beverages', 'organic almond milk','30 calories per serving','organicAlmondmilk.png'),
('34123', 6, 'beverages', 'pepsi','10 calories per serving','pepsi.png'),
('34124', 1, 'beverages', 'pom juice','10 calories per serving','POMjuice.png'),
('34125', 24, 'beverages', 'powerade','60 calories per serving','powerade.png'),
('34126', 12, 'beverages', 'sparkling water', '60 calories per serving','sparklingwater.png'),
('34127',12, 'beverages', 'sprite zero', '60 calories per serving','SpriteZero.png'),
('34128', 4, 'beverages', 'starbucks coffee', '60 calories per serving','stabuckscofyee.png'),
('34129', 12, 'beverages', 'vitamin water','20 calories per serving','vitaminwater.png'),
('34130', 1, 'beverages', 'whole milk','40 calories per serving','WholeMilk1gallon.png'),
('35111', 1, 'fruits', 'artichoke', '30 calories per serving','Artichoke.png'),
('35112', 1, 'fruits', 'avocado','60 calories per serving','avocado.png'),
('35113', 1, 'fruits', 'beets', '10 calories per serving','Beets.png'),
('35114', 1, 'fruits', 'broccoli','20 calories per serving','Broccoli.png'),
('35115', 1.0, 'fruits', 'brussels sprouts','10 calories per serving','brusselsSprouts.png'),
('35116', 0.5, 'fruits', 'butternut squash', '30 calories per serving','ButternutSquash.png'),
('35117', 1.0, 'fruits', 'carrots', '50 calories per serving','carrots.png'),
('35118', 1, 'fruits', 'cauliflower', '70 calories per serving','cauliflower.png'),
('35119', 1.0, 'fruits', 'celery', '10 calories per serving','celery.png'),
('35120', 1, 'fruits', 'cilantro', '5 calories per serving','cilantro.png'),
('35121', 5, 'fruits', 'corn', '15 calories per serving','Corn.png'),
('35122', 3, 'fruits', 'cucumber', '20 calories per serving', 'cucumber.png'),
('35123', 1, 'fruits', 'eggplant', '50 calories per serving','eggplant.png'),
('35124', 3, 'fruits', 'garlic', '10 calories per serving','Garlic.png'),
('35125', 1.0, 'fruits', 'green beans', '20 calories per serving','Greenbeans.png'),
('35126', 1, 'fruits', 'green cabbage','greenCabbage.png', '60 calories per serving'),
('35127', 1, 'fruits', 'green onion', 'greenOnion.png', '60 calories per serving'),
('35128', 1, 'fruits', 'iceberg lettuce','15 calories per serving','icebergLettuce.png'),
('35129', 1, 'fruits', 'okra', '70 calories per serving','okra.png'),
('35130', 1, 'fruits', 'potato', '10 calories per serving','potato.png'),
('35131', 1.0, 'fruits','red on the vine tomatoes', '50 calories per serving', 'redOnTheVineTomatoes.png'),
('35132', 1.5, 'fruits', 'roma tomatoes','10 calories per serving','RomaTomatoes.png'),
('35133', 1.0, 'fruits', 'bell pepper','60 calories per serving','bellpepper.png'),
('35134', 2.0, 'fruits', 'white mushroom','30 calories per serving','slicedWhiteMushroom.png'), 
('35135', 1.0, 'fruits', '10 calories per serving', 'yams','Yams.png'),
('35136', 1.0, 'fruits','yellow onion', '20 calories per serving', 'yellowOnion.png'),
('35137', 2.0, 'fruits', 'yellow squash', '30 calories per serving','yellowSquash.png'),
('35138', 1.0, 'fruits', 'zucchini squash', '65 calories per serving','ZucchiniSquash.png');

